server:
  port: 9000
  read-timeout: 60
  write-timeout: 60

user_server:
  port: 9001
  read-timeout: 60
  write-timeout: 60

app:
  #run-mode:debug/release
  run-mode: debug
  pagesize: 10
  log-path: ../log/debug.log
  identity-key: idname

database:
  type: mysql
  user: admin
  password: admin1234
  host: 127.0.0.1:3306
  name: gin-vue
  table-prefix: go_

redis:
  addr: 127.0.0.1:6379
  pass: 
  db: 0
  timeout: 1000
  expired-time: 3600

rabbitmq:
  addr: 127.0.0.1
  port: 5672
  user: guest
  pass: guest